server:
  port: 8080
  contextPath: /monese-services
spring:
  application:
    name: monese-services
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/monese?serverTimezone=UTC&useLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        time_zone: UTC
monese:
  swagger:
    groupname: monese-services
    title: Monese Banking Services Platform
    description: Monese Banking Services Platform
    version: 1.0.0
    license: Monese
    licenseurl: www.monese.com
  server:
    link-verication-url: http://localhost:8080
    agreement:
      processing:
        time: 0 0 0 * * *
        zone: Asia/Dubai
    support: 
      email: 